### PR TITLE
Update install section

### PR DESCRIPTION
**Pull request by jubianchi**
See #11

### CODE REVIEW

**Comment by jubianchi** [comment]
@Hywan in this case, the two constraints (`~0.0` and `0.*`) are stricly equal: they'll both match `>=0.0.0 <1.0.0` (see http://jubianchi.github.io/semver-check/)

**Comment by Hywan** [comment]
Yup I know. I was thinking about consistency with Hoa's installation sections.

**Comment by Hywan** [comment]
:+1: for me.

**Comment by jubianchi** [comment]
@Hywan ha I did not look at other Hoa's readmes. If you use to use `~0.0` I'll update this one ;)

**Comment by jubianchi** [comment]
BTW, I failed : we have a `1.*` tag so I have to update the readme.

@Hywan ok for `~1.0` ?

**Comment by Hywan** [comment]
:+1:

**Pull request merged**
